### ISSUE TITLE
某政府网站新闻页面，过滤不到正文

### ISSUE THREAD

**Issue by Shawn-fung** [GeneralNewsExtractor/GeneralNewsExtractor#114]
url地址如下
http://www.hnsjct.gov.cn/sitesources/hnsjct/page_pc/scdc/sggb/zjsc/article9b99a830a8eb4e839837a7c88a0ee12f.html

extractor.extract(response.content.decode("utf-8"),body_xpath='//div[@class="article-cont"]')
加body_xpath，，会报错，超出列表范围

**Comment by kingname** [comment]
不要直接使用 requests 获取的源代码。要通过浏览器渲染以后复制出源代码来。
