### ISSUE TITLE
提取时，中文逗号，全变成英文逗号了

### ISSUE THREAD

**Issue by billgetjoy** [GeneralNewsExtractor/GeneralNewsExtractor#121]
例如正文：
任何整形项目都不可能做到十全十美，任何手术都是有风险的。
提取后：
任何整形项目都不可能做到十全十美,任何手术都是有风险的。

标题中的中文逗号也是同样会变成英文逗号

**Comment by kingname** [comment]
是因为在预处理的时候，会对所有非标准符号进行标准化，中文逗号标准化以后就会变成英文逗号。这确实是一个 bug。这个问题对你影响大吗？

**Comment by billgetjoy** [comment]
> 

影响不大，可忽略。自己排查程序时发现，故反馈下。

**Comment by kingname** [comment]
在master分支中已经修复这个问题。
