### ISSUE TITLE
抽取 https://www.gov.cn/gongbao/content/2007/content_711039.htm 的正文，结果不符合预期

### ISSUE THREAD

**Issue by linchen059** [GeneralNewsExtractor/GeneralNewsExtractor#129]
**bug的现象**

1. 你期望的返回是？（如截图所示）
2. 实际GNE给你的返回是？（如截图所示）

**如何复现**

1. 目标地址：[全国人民代表大会常务委员会 关于批准财政部发行特别国债购买外汇及 调整2007年末国债余额限额的决议](https://www.gov.cn/gongbao/content/2007/content_711039.htm)
2. 调用代码
```
response = requests.get('https://www.gov.cn/gongbao/content/2007/content_711039.htm')
response.encoding = response.apparent_encoding
html_content = response.text
extractor = GeneralNewsExtractor()
result = extractor.extract(html_content, noise_node_list=['//div[@class="comment-list"]'])
print(result)
return result['content']
```

**屏幕截图**
<img width="1114" alt="image" src="https://github.com/GeneralNewsExtractor/GeneralNewsExtractor/assets/11939613/9d5af460-8d09-4662-8ed1-d910d941d914">

<img width="1465" alt="image" src="https://github.com/GeneralNewsExtractor/GeneralNewsExtractor/assets/11939613/27cac59d-c49b-4ef9-a50e-01472964f923">

**使用环境:**
 - OS: [macOS 12.3.1 ]
 - Python版本 [3.7.2]
 - GNE版本 [0.3.0]

**Comment by kingname** [comment]
收到，原因是正文比较短，在打分是时跟导航栏没有太多区分。你可以先把导航栏加到noise_node_list里面来过去

**Comment by linchen059** [comment]
谢谢回复。经分析，发现html网页源码不规范，存在两个 </html> 结束符，导致 gne 识别结果不符合预期。调用 gne 方法前，提前去除不规范的 </html> 标签后问题解决。

**Comment by linchen059** [comment]
补充：如果 gne 能做个小优化，兼容这种不规范 html 就更好了，这样其他使用者就不用再趟一次坑了。

**Comment by kingname** [comment]
好的，我今晚更新一下。

**Comment by kingname** [comment]
你可以先使用如下代码来预处理一下HTML

```python
from lxml.html import fromstring

arsed_html = fromstring(html_doc)

# 输出修复后的HTML
fixed_html = html.tostring(parsed_html, pretty_print=True, method="html", encoding='unicode')
```

**Comment by linchen059** [comment]
👍👍👍  &&  谢谢

**Comment by kingname** [comment]
我今天看了一下。其实GNE的文档里面说了，传入GNE的应该是经过浏览器渲染的HTML,而不是直接从requests获取的html。浏览器渲染的时候会自动修复html标签的异常。渲染后的html可以正常提取

**Comment by kingname** [comment]
https://github.com/GeneralNewsExtractor/GeneralNewsExtractor/releases/tag/v0.3.1
