### ISSUE TITLE
为GNE写一个效果测试页面

### ISSUE THREAD

**Issue by kingname** [GeneralNewsExtractor/GeneralNewsExtractor#49]
![image](https://user-images.githubusercontent.com/5440523/70416512-341fb380-1a9a-11ea-975b-2a33ba11f333.png)

**Comment by ego008** [comment]
发现有两个在线测试
https://pylist.com/tools/gne 这个可以调试过滤条件
https://general-news-extractor-demo.stayin.cn/ 这是简单的demo

**Comment by kingname** [comment]
厉害厉害，我去联系一下这两个网站的作者
